name: Build Windows EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "static;static" --hidden-import "pydantic" --hidden-import "databases" --hidden-import "sqlalchemy" main.py

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: windows-exe
          path: dist/
